// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BackendML.Model
{
    public class ModelInput
    {
        [ColumnName("Timestamp"), LoadColumn(0)]
        public string Timestamp { get; set; }


        [ColumnName("Number"), LoadColumn(1)]
        public float Number { get; set; }


        [ColumnName("MemBytes"), LoadColumn(2)]
        public float MemBytes { get; set; }


        [ColumnName("InBytes"), LoadColumn(3)]
        public float InBytes { get; set; }


        [ColumnName("OutBytes"), LoadColumn(4)]
        public float OutBytes { get; set; }


        [ColumnName("CpuPct"), LoadColumn(5)]
        public float CpuPct { get; set; }


    }
}
