// This file was auto-generated by ML.NET Model Builder. 

using System;
using BackendML.Model;

namespace BackendML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Number = 3.52F,
                MemBytes = 7.631966E+09F,
                InBytes = 1152221F,
                CpuPct = 0.2349F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual OutBytes with predicted OutBytes from sample data...\n\n");
            Console.WriteLine($"Number: {sampleData.Number}");
            Console.WriteLine($"MemBytes: {sampleData.MemBytes}");
            Console.WriteLine($"InBytes: {sampleData.InBytes}");
            Console.WriteLine($"CpuPct: {sampleData.CpuPct}");
            Console.WriteLine($"\n\nPredicted OutBytes: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
