// This file was auto-generated by ML.NET Model Builder.

using System;
using Microsoft.ML.Data;

namespace WorkerService.Entities
{
    public class PredictionOutput
    {
        public float Score { get; set; }
    }
}