// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML.Data;

namespace WorkerService.Entities
{
    public class PredictionInputCpupct
    {
        [ColumnName("Timestamp"), LoadColumn(0)]
        public string Timestamp { get; set; }
    }
}